language: php
php:
- '5.6'
cache:
  directories:
  - node_modules
before_script:
- nvm install v6.8.1
- npm install
script:
- npm run info
- find . \( -name '*.php' \) -exec php -lf {} \;
after_success:
- bash ./bin/deploy.sh
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=sysken@aitech.ac.jp
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=sysken@aitech.ac.jp
  - secure: sI0W2ZkbLHizXv2Y4EBh1wJrI4rTbfN5YhIgtToUX7+5dPpQSnqFrFZNiqKNJ4K0vM+Wt6XeJLXJJ4lpMBiJWVM0gspLYroExIpVzcpZ8yRcFsVWD98l0LXJDRhmpgr9hn7yY1TF+ebm38bc45U0OnqMrfZcLa6PgSXHOE1e6GGb+blkRMomE/KUATluL7upIf1IqjhSnNqJJx5yTGua7pSPJryvgH8bBoDl65GUwN7abUWSfEhwpa3eEsZn2+GT2ZcYo76MCBFop+RX/uRv/a4QcBNRFYH4wjwxcf2nCdTAvbg8+MQ3xKCXPN+IZxZGwsdxP0yE3J5wMARxqjqqY5NoMIBzW8zy3U2xtWpOSAvwjSDp5ewPANeafQi/w2HXONC+VvEBOMdov5SVE5E8SRUuuLUekeaXM8NnAOpW93oU85uyj9XpGvMaGHFPwFqTjTr+2dWpVJCVV66TasMECOT448T/Vmef1rDjQ9Ujxn/z4EVPfSU7mzSXVAwIPt3VAP7fdRgIma3MSb7esbXrE1+ic/yCe3zDzI3+kkIaUz7HG6r/nkrPvzksc6PgjzyDw16jbSJABmBLQEa17qcoX7ww72cqE3Nb13iYOmV0jyOe99McVUbe1itRAX4T8HyYdIFaMsRdwL++Hn6cdEYbRQtqUuQtlUiTDKSzn2aih3k=
notifications:
  slack:
    secure: kNd5q4Us57M2n+w9NP1W81PEXBRUTM/4UceT0wMGo1wWoQTsGjvUEIEnyX/Ut6IgPIUQrKSgosFZ3+OBTHphqjtB0PMZQ1SG3vOhLNgpPEyJUTChl4g6J01BPhspt3W+lT3QJf8J9vI00LAOCaHme7/3pbPywa6abkfFR7m767u3TunXsnv7FQLTEfFJ94aVPjZi/YLw0lZoW1cVvOyyDVRBrhZzmkZJ/uBzOcTEhcvfWp8311WucIkSaPPrQLjrggyvPTNn+mepQ6bpssxbuhdSAeisBbimyrnT7EGxj2xS/vVW3QIfb2dzpp3ydKkGr/H+K9RUyIccvrp0m3jqHcTfF/7UaXN7dFR7sGxepjKFnSSxNKaM8dqDuVHGIC04CE4rwwforeUqqhz0RlvSNXKywUv5UPdw6HpGReqrNNxXexoV/ZEkSJn+WdqiKlHWqigELMkS2/GYvswXsiNWcgf64KCXC5Ov9rId+EfublqgXU3KY+Azul1AATo9yhyi3ktqVYIQqXOaUeybMze3ZsBKWnsp1f3U+gBlo456Grkal6ksn00HThfjbne8W3HM2G4+4yiRv5NXXV19S5Nnrh2RNzGcYyZBfwY0PcDiJr0RWXZ2PaWUNrC5+ZJURp21YNi5eZnW2vUNUPzZtqR8fiehde8rT5j+ULsgbHA/4Hw=
