language: php
php:
- '5.6'
cache:
  directories:
  - node_modules
before_script:
- nvm install v6.8.1
- npm install
script:
- npm run info
- find . \( -name '*.php' \) -exec php -lf {} \;
after_success:
- bash ./bin/deploy.sh
env:
  global:
    - GIT_COMMITTER_NAME=travis-ci
  	- GIT_COMMITTER_EMAIL=sysken@aitech.ac.jp
  	- GIT_AUTHOR_NAME=travis-ci
  	- GIT_AUTHOR_EMAIL=sysken@aitech.ac.jp
    - secure: sI0W2ZkbLHizXv2Y4EBh1wJrI4rTbfN5YhIgtToUX7+5dPpQSnqFrFZNiqKNJ4K0vM+Wt6XeJLXJJ4lpMBiJWVM0gspLYroExIpVzcpZ8yRcFsVWD98l0LXJDRhmpgr9hn7yY1TF+ebm38bc45U0OnqMrfZcLa6PgSXHOE1e6GGb+blkRMomE/KUATluL7upIf1IqjhSnNqJJx5yTGua7pSPJryvgH8bBoDl65GUwN7abUWSfEhwpa3eEsZn2+GT2ZcYo76MCBFop+RX/uRv/a4QcBNRFYH4wjwxcf2nCdTAvbg8+MQ3xKCXPN+IZxZGwsdxP0yE3J5wMARxqjqqY5NoMIBzW8zy3U2xtWpOSAvwjSDp5ewPANeafQi/w2HXONC+VvEBOMdov5SVE5E8SRUuuLUekeaXM8NnAOpW93oU85uyj9XpGvMaGHFPwFqTjTr+2dWpVJCVV66TasMECOT448T/Vmef1rDjQ9Ujxn/z4EVPfSU7mzSXVAwIPt3VAP7fdRgIma3MSb7esbXrE1+ic/yCe3zDzI3+kkIaUz7HG6r/nkrPvzksc6PgjzyDw16jbSJABmBLQEa17qcoX7ww72cqE3Nb13iYOmV0jyOe99McVUbe1itRAX4T8HyYdIFaMsRdwL++Hn6cdEYbRQtqUuQtlUiTDKSzn2aih3k=
